### ISSUE TITLE
How to use LLVM XRAY ?

### ISSUE THREAD

**Issue by meftunca** [bazel-contrib/toolchains_llvm#233]
I want to use it as a profiling tool in my project, but I don't know how to use it. I would be very happy if people with knowledge can help.

**Comment by nolen777** [comment]
Sorry, I don't know anything about this.

**Comment by siddharthab** [comment]
It does not look like it needs any specific support in this project, seems like just adding a feature flag. We can revisit if people try it and something breaks.
