### ISSUE TITLE
bzlmod sysroot example test not working

### ISSUE THREAD

**Issue by steve-261370** [bazel-contrib/toolchains_llvm#234]
I cloned the repo and went into the `tests` directory. 

The following command, which uses the llvm sysroot toolchain, with bzlmod disabled, works:

`bazel test --enable_bzlmod=false --extra_toolchains=@llvm_toolchain_with_sysroot//:cc-toolchain-x86_64-linux //:all`

But when bzlmod is enabled, the build fails

`bazel test --enable_bzlmod=true --extra_toolchains=@llvm_toolchain_with_sysroot//:cc-toolchain-x86_64-linux //:all`

The error returned is:

`
ERROR: An error occurred during the fetch of repository 'toolchains_llvm~override~llvm~llvm_toolchain_with_sysroot':
   Traceback (most recent call last):
        File "/home/steve-261370/.cache/bazel/_bazel_steve-261370/fe79d53e53f1045ef52b7f75d9f074d8/external/toolchains_llvm~override/toolchain/internal/configure.bzl", line 87, column 57, in llvm_config_impl
                llvm_dist_path_prefix = _pkg_path_from_label(llvm_dist_label)
        File "/home/steve-261370/.cache/bazel/_bazel_steve-261370/fe79d53e53f1045ef52b7f75d9f074d8/external/toolchains_llvm~override/toolchain/internal/common.bzl", line 144, column 13, in pkg_path_from_label
                if label.workspace_root:
Error: 'workspace_root' is not allowed on invalid Label @[unknown repo 'llvm_toolchain_llvm' requested from @toolchains_llvm~override]//:BUILD.bazel
`

It looks like the github tests only run through the sysroot tests with bzlmod=false.  I am running bazel 6.4.0 on a debian-based system.

**Comment by patrice332** [comment]
Hitting the same issue

**Comment by archen** [comment]
change the lines to use the canonical name like this:

```
llvm.toolchain(
    name = "llvm_toolchain_with_sysroot",
    llvm_versions = LLVM_VERSIONS,
    sysroot = {
        "linux-x86_64": "@@org_chromium_sysroot_linux_x64//:sysroot",
    },
    # We can share the downloaded LLVM distribution with the first configuration.
    toolchain_roots = {
        "": "@@llvm_toolchain_llvm//",
    },
)
```

**Comment by fmeum** [comment]
We are also hitting this. For now, you can work around this by specifying a canonical label:

```
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "16.0.4",
    sysroot = {
        # The extension doesn't handle labels to external repositories correctly: It does not map
        # apparent names such as @org_chromium_sysroot_linux_x64 to the correct Bazel-internal
        # canonical repository name. As a workaround, specify the canonical name directly.
        # TODO: Get rid on this dependency of Bazel implementation details when toolchains_llvm
        #       offers an attribute of type label rather than string.
        "linux-x86_64": "@@_main~_repo_rules~org_chromium_sysroot_linux_x64//:sysroot",
    },
)
use_repo(llvm, "llvm_toolchain")
```

**Comment by mering** [comment]
@fmeum what is the canonical label for a non-module dependency from a dependency.

Let's say I have a module "B" which has non-module-extensions.bzl which defines "C" loaded via `use_repo()`.
When I now have a dependency `bazel_dep(name=B)` in module "A", how can I access the toolchain "C" then?

**Comment by mering** [comment]
How can I find out the canonical label of a transitive non-module dependency (made visible via `use_repo()`)?

**Comment by fmeum** [comment]
You can `bazel query --canonical_labels` for it using a regular label.

**Comment by mering** [comment]
> You can `bazel query --canonical_labels` for it using a regular label.

Thanks for the hint. I got it working by using [`--consistent_labels`](https://github.com/bazelbuild/bazel/issues/17864).
