### ISSUE TITLE
Linux AArch64 build fails with missing include <features.h>

### ISSUE THREAD

**Issue by dprogm** [bazel-contrib/toolchains_llvm#247]
**What is the issue?**

When compiling a simple program that includes the `<algorithm>` header the compiler is raising the following error:

```bash
external/toolchains_llvm~override~llvm~llvm_toolchain_llvm/bin/../include/c++/v1/__config:261:14: fatal error: 'features.h' file not found
#    include <features.h>
```

**How did you compile?**

Used this `.bazelrc`
```
build --cxxopt=-std=c++17 --enable_bzlmod --incompatible_enable_cc_toolchain_resolution
```

**On which platform did you compile?**

AArch64 Linux, Ubuntu 22.04

**What version did you use?**

[Version 0.10.3](https://github.com/grailbio/bazel-toolchain/releases/tag/0.10.3) with LLVM 17.04

This looks like a sysroot issue?

**Comment by siddharthab** [comment]
`features.h` is a libc header. Short of a resolution on #155, you need to install glibc in your OS.

On Ubuntu 22.04, unless you are cross-compiling, the apt package `libc6-dev` is what you need (although it almost always comes preinstalled).
```
sudo apt-get install libc6-dev && (dpkg -L libc6-dev | grep features.h)
```

If this is not enough, please reopen the issue.
