### ISSUE TITLE
Add support for LLVM 17.x.x

### ISSUE THREAD

**Issue by joseluis8906** [bazel-contrib/toolchains_llvm#276]
Please add support for clang 17.x.x.

**Comment by jsharpe** [comment]
Support is already there for some versions of 17.x.x:
https://github.com/bazel-contrib/toolchains_llvm/blob/1d58ed6bd43de852652c5665f73da133a2a72487/toolchain/internal/llvm_distributions.bzl#L317
Please file a PR to update that file if there are other release artifacts that are missing from the upstream (unfortunately upstream isn't very consistent in how they upload their binary releases)

**Comment by siddharthab** [comment]
I will make a release this week.

**Comment by sandordargo** [comment]
Thank you so much, @siddharthab
