### ISSUE TITLE
Use deb packages as binary sources

### ISSUE THREAD

**Issue by layus** [bazel-contrib/toolchains_llvm#345]
I wonder if there is a way to use deb packages hosted on https://apt.llvm.org/ as binary source. While binary packages are provided by volunteers hand there is uneven support for systems, the apt repo contains releases for each llvm version and several ubuntu versions.

Has someone ever tried that ? How hard would it be to redirect toolchains_llvm to a local repository_rule containting the unpacked and merged packages ?

**Comment by zaucy** [comment]
I'm also interesting in this, but I haven't tried it yet.

We could possibly use these deb packages as well http://ftp.debian.org/debian/pool/main/l/llvm-toolchain-18/

**Comment by mering** [comment]
Should no longer be needed with #392
