### ISSUE TITLE
std::format not available (Macos aarch64)

### ISSUE THREAD

**Issue by MarcoBonino** [bazel-contrib/toolchains_llvm#413]
Hello!

I'm getting the following error when running from Apple M3:
`src/main.cpp:5:23: error: no member named 'format' in namespace 'std'`

I have a simple reproducer in: https://github.com/MarcoBonino/bazel_llvm_toolchains
Simply try with `bazel build src:main --cxxopt=-std=c++20`

If I do not register the toolchain (using the default) I can successfully compile.

Am I doing something wrong or some header is missing in the toolchain ?

Thanks!

**Comment by jmillikin** [comment]
Your `MODULE.bazel` sets `llvm_version = "16.0.0"`, but `std::format` didn't stabilize in libc++ until LLVM 17.

Can you try with `llvm_version = "17.0.6"`? On my machine, your example successfully builds with that version.
